### ISSUE TITLE
`transvar/docs/source/features.rst` content incomplete

### ISSUE THREAD

**Issue by die4live** [zwdzwd/transvar#10]
seems those lines are cut by fixed width

**Comment by zwdzwd** [comment]
do you mean those on the documentation? Yes, those are cut by fixed width for aesthetic purposes. and only happen in the documentation, not in actual output. not sure if that's what you are asking?

**Comment by zwdzwd** [comment]
Ah, I see what you mean, let me find out what's going on. Thanks for reporting!

**Comment by zwdzwd** [comment]
Fixed. 

Thanks.
