### ISSUE TITLE
ganno batch example

### ISSUE THREAD

**Issue by cboustred** [zwdzwd/transvar#12]
Please could you post an example of a `ganno` (genomic co-ordinates to HGVS) batch input example file and the command I would use to run it? 

e.g. if I had a file a bit like this (only a quick example)

```
# chrom pos ref alt preferred_transcript
chr6 1234 A T ENST001234
chr10 4321 A C ENST004321
etc...
```

Whats the `ganno` command to run to run transvar and return the corresponding HGVS co-ordinates?

Thanks in advance!

**Comment by zwdzwd** [comment]
Hi,
I updated the document with two examples,
http://transvar.readthedocs.io/en/latest/annotation_from_genomic_level.html#batch-processing
Also I found a problem while parsing using "-a". So I updated the code as well. if you find an issue, try update your install. 

Thanks
