### ISSUE TITLE
Reference sequence doesn't exist error after following example

### ISSUE THREAD

**Issue by kuanlinhuang** [zwdzwd/transvar#14]
I followed the example code to download hg19 but still get the reference sequence doesn't exist error. 
$ transvar config --download_anno --refversion hg19
$ transvar config --download_ref --refversion hg19
$ transvar panno -i 'PIK3CA:p.E545K' --ucsc --ccds
Reference sequence doesn't exist
samtools faidx file doesn't exist for reference
Traceback (most recent call last):
  File "/usr/local/bin/transvar", line 30, in <module>
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/transvar/anno.py", line 178, in main
    db = AnnoDB(args, config)
  File "/usr/local/lib/python2.7/site-packages/transvar/annodb.py", line 49, in __init__
    faidx.init_refgenome(args.reference if args.reference else None)
  File "/usr/local/lib/python2.7/site-packages/transvar/faidx.py", line 93, in init_refgenome
    refgenome = RefGenome(r) if r else None
  File "/usr/local/lib/python2.7/site-packages/transvar/faidx.py", line 22, in __init__
    self.load_faidx()
  File "/usr/local/lib/python2.7/site-packages/transvar/faidx.py", line 33, in load_faidx
    for line in self.faidx_handle:
AttributeError: RefGenome instance has no attribute 'faidx_handle'

**Comment by zwdzwd** [comment]
Hi, sorry to see this trouble. If you give "transvar current" what is the output? is the file in the reference slot accessible?

**Comment by kuanlinhuang** [comment]
Thank you for the quick reply. Here it is; it's not available:
$ transvar current
reference version: hg19
reference: /Users/khuang/.transvar.download/hg19.fa
Available databases: 
refseq: /Users/khuang/.transvar.download/hg19.refseq.gff.gz.transvardb
ccds: /Users/khuang/.transvar.download/hg19.ccds.txt.transvardb
ensembl: /Users/khuang/.transvar.download/hg19.ensembl.gtf.gz.transvardb
gencode: /Users/khuang/.transvar.download/hg19.gencode.gtf.gz.transvardb
ucsc: /Users/khuang/.transvar.download/hg19.ucsc.txt.gz.transvardb
aceview: /Users/khuang/.transvar.download/hg19.aceview.gff.gz.transvardb
known_gene: /Users/khuang/.transvar.download/hg19.knowngene.gz.transvardb

$ ls /Users/khuang/.transvar.download/hg19.fa
ls: /Users/khuang/.transvar.download/hg19.fa: No such file or directory
$ ll /Users/khuang/.transvar.download/hg19.refseq.gff.gz.transvardb
ls: /Users/khuang/.transvar.download/hg19.refseq.gff.gz.transvardb: No such file or directory

**Comment by zwdzwd** [comment]
It turned out to be an issue after recent accommodation of python 3. The downloading wasn't properly finished. I just uploaded a fix. You should be able to get it through 
==
pip install -U transvar
==
if you installed through pip

I have tested it on my end. Previously I didn't catch it due to a fall-back downloading that relies on HTTP-requests. Let me know if this fixed problem on your end.

Thanks for the feedback!

**Comment by kuanlinhuang** [comment]
Yes that worked. Thank you zwdzwd!
