### ISSUE TITLE
failed annotation complex variant

### ISSUE THREAD

**Issue by kjass001** [zwdzwd/transvar#26]
Hi,
We annotated vcf of clinical sample with a clinically-relevant insertion exon 20.
- alignment bwa-mem
- variant calling Vardict
- annotation TransVar
It appears that TransVar cannot annotate following 'complex' mutation (in-frame insertion +adjacent SNV) 
![image](https://user-images.githubusercontent.com/39410349/48057209-bbbe3300-e1b3-11e8-8e1b-907559291389.png)

Vardict output vcf (marked line 78% VAF):
![image](https://user-images.githubusercontent.com/39410349/48057144-95989300-e1b3-11e8-809a-96229c42a438.png)

Transvar annotated and filtered:
![image](https://user-images.githubusercontent.com/39410349/48057857-566b4180-e1b5-11e8-9ba9-f0dd2e94249b.png)

-->no annotation. Any options possible to achieve adequate annotation?
Thanks for help!

**Comment by kennethgeerts** [comment]
In case it could help, this is what vardict logs:

`[vcf_parse_mutation] warning: Invalid VCF line: chr7     55249013        .       A       GGTT    371     PASS    .      GT:DP:VD:AD:AF:RD:ALD   1/0:1302:1019:263,1019:0.7826:263,0:1019,0`

**Comment by mmoisse** [comment]
I solved the issue by changing the definition for MNV from ``len(ref) > 1 and len(alt) > 1`` to ``len(ref) > 1 or len(alt) > 1`` 

 cfr commit https://github.com/zwdzwd/transvar/pull/33/commits/344f253ffacebbcbb4381c166a534fd0ccb17f87

**Comment by zwdzwd** [comment]
Thanks for the fix. I merged this change.
