### ISSUE TITLE
No `CdsStartLoss` and `CdsStopLoss` functionality

### ISSUE THREAD

**Issue by jpiper** [zwdzwd/transvar#4]
It appears that whilst `CdsStartLoss` and `CdsStopLoss` appear in the documentation, this functionality does not exist.

**Comment by zwdzwd** [comment]
sorry, it was CdsStartLoss and CdsStopLoss, but got changed to CdsStartSNV recently. The documentation is updated. http://transvar.readthedocs.io/en/latest/interpret_variant_consequence.html. CdsStartDeletion and CdsStopDeletion is also added. please see
http://transvar.readthedocs.io/en/latest/annotation_from_genomic_level.html#coding-start-and-stop

I have notice some missing with the CCDS database. I am looking into this. But surely let me know if you see other counter-examples.

Thanks,
